### ISSUE TITLE
[Bug] Reddit API not working with Windows Installer - PRAW error?

### ISSUE THREAD

**Issue by penfold1972** [OpenBB-finance/OpenBBTerminal#1831]
**Describe the bug**
Reddit API does not appear to be working on Windows v1.3.0

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior
I have installed a fresh copy of openBBterminal, put my keys in the .env file and started up OpenBBterminal. The keys section says they are loaded, but fail. When I set DEBUG and try to load WSB, I am able to get the error "AttributeError: '_NotSet' object has no attribute 'lower'" apparently from line 36 in file praw\config.py as seen in the screenshot.

If DEBUG is not set, then the program doesn't crash, but I only get the message "Error: '_NotSet' object has no attribute 'lower'" before it brings me back to the prompt.
**Screenshots**
![image](https://user-images.githubusercontent.com/24441474/168877543-e85285d8-e857-4021-b326-305be04c7e98.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Python version 3.9.6

**Additional context**
Add any other information that you think could be useful for us.

I have installed python and made a little reddit testing script using praw using the same keys and it works fine. I suspect praw in the windows installer needs to be updated, but I don't know how to confirm that.

**Comment by deeleeramone** [comment]
![Screen Shot 2022-05-19 at 10 13 29 AM](https://user-images.githubusercontent.com/85772166/169358934-19dbd3ab-54f2-48db-a0c0-2de1322375c5.png)

**Comment by DidierRLopes** [comment]
Hey @penfold1972 

Thanks for the reporting. This is it: https://github.com/praw-dev/praw/issues/1016

It should be fixed in the next version, thank you 🙌
