### ISSUE TITLE
[Bug] Economy/Events - Error: 'Namespace' object has no attribute 'end'. Function is dead

### ISSUE THREAD

**Issue by JacksonVasconcelos** [OpenBB-finance/OpenBBTerminal#2529]
Events command is not returning a value after update.

**To Reproduce**
Using OpenBBTerminal v1.6 (Installed manually on Windows) and after update (command 'update') to v1.17 the 'economy/events' no longer works. Not functional either using the v1.18 Windows installer. Command 'economy/events' returns "Error: 'Namespace' object has no attribute 'end'".

**Screenshots**
![image](https://user-images.githubusercontent.com/10968371/189684261-bbba4a59-ed9d-4460-9734-d1f50d3ba2b2.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Python version 3.9.13

**Comment by deeleeramone** [comment]
Hello,

Thanks for reporting, I am also able to recreate, from the main branch of the repository. 
![Screen Shot 2022-09-12 at 7 59 42 PM](https://user-images.githubusercontent.com/85772166/189797944-a82e957f-bc2c-43d7-b66e-df1a5f3a6baa.png)

**Comment by dominion314** [comment]
Any update on this issue?
